CVE-2022-24521 RCA
googleprojectzero/0days-in-the-wild pull request #13
Opened 2022-04-26 07:10 UTC by pixiepointsec

2022-04-27 15:59 UTC, maddiestone requested changes
Thank you! Just a few modifications, please.

2022-04-28 05:09 UTC, pixiepointsec commented
Thanks for pointing out the modifications to make! Please let me know if there's others.

2022-04-28 16:25 UTC, maddiestone approved these changes
Looks great, thank you!

2022-04-28 16:25 UTC, maddiestone commented
Thank you, this looks great! Once you sign the CLA we'll be able to merge it in.

2022-04-29 23:13 UTC, pixiepointsec commented
It should have been signed. Can you trigger a rescan and see if it works? Thanks.

2022-04-30 17:45 UTC, merged

2022-04-30 17:45 UTC, maddiestone commented
Thank you so much!